### PR TITLE
Feature/21 validation update

### PR DESCRIPTION
**Pull request by easingthemes**
https://github.com/nice-registry/nice-package/issues/21

### CODE REVIEW

**Comment by zeke** [comment]
Thanks! In response to this PR, I've set up semantic-release in https://github.com/nice-registry/nice-package/pull/23 which will now automatically release merged PRs to GitHub and npm.

Because this change affects validation, I think we should consider it a breaking change. 

Can you add a commit with `BREAKING CHANGE` in the body? Note that `BODY` technically means everything after the first line of the commit. See https://www.conventionalcommits.org/en/v1.0.0-beta.2/

If you're using bash, you can start a multi-line commit using a single-quote then write the rest of the message on the following lines:

```
git commit --allow-empty -m 'fix: do not require description

This is a BREAKING CHANGE'
````

PS I know this is a lot of song and dance. Good luck and let me know if you get stuck!

**Comment by zeke** [comment]
Hey @easingthemes -- sorry I let this fall through the cracks for nearly a year. Are you able to make the changes I requested above?

**Comment by feross** [comment]
I was able to use the Squash and Merge feature on GitHub to edit the commit message as specified :)

**Pull request merged**
